locustfile = ./scenarios/http/gateway/existing_user_get_operations/scenario.py
spawn-rate = 20
run-time = 5m
headless = true
users = 200
html = ./scenarios/http/gateway/existing_user_get_operations/report.html